import { Types, CodegenPlugin } from '@graphql-codegen/plugin-helpers';
import addPlugin from '@graphql-codegen/add';
import { concatAST, parse } from 'graphql';
import { resolve, relative, join } from 'path';
import { groupSourcesByModule, stripFilename, normalize } from './utils';
import { buildModule } from './builder';

export type ModulesConfig = {
  /**
   * @name baseTypesPath
   * @type string
   * @description Required, should point to the base schema types file.
   * The key of the output is used a the base path for this file.
   *
   * @example
   * ```yml
   * generates:
   * src/:
   *  preset: modules
   *  presetConfig:
   *    baseTypesPath: types.ts
   *  plugins:
   *    - typescript-resolvers
   * ```
   */
  baseTypesPath: string;
  /**
   * @name cwd
   * @type string
   * @description Optional, override the `cwd` of the execution. We are using `cwd` to figure out the imports between files. Use this if your execuion path is not your project root directory.
   * @default process.cwd()
   *
   * @example
   * ```yml
   * generates:
   * src/:
   *  preset: modules
   *  presetConfig:
   *    baseTypesPath: types.ts
   *    cwd: /some/path
   *  plugins:
   *    - typescript-resolvers
   * ```
   */
  cwd?: string;
  /**
   * @name importTypesNamespace
   * @type string
   * @description Optional, override the name of the import namespace used to import from the `baseTypesPath` file.
   * @default Types
   *
   * @example
   * ```yml
   * generates:
   * src/:
   *  preset: modules
   *  presetConfig:
   *    baseTypesPath: types.ts
   *    importTypesNamespace: core
   *  plugins:
   *    - typescript-resolvers
   * ```
   */
  importTypesNamespace?: string;
  /**
   * @name filename
   * @type string
   * @description Required, sets the file name for the generated files.
   *
   * @example
   * ```yml
   * generates:
   * src/:
   *  preset: modules
   *  presetConfig:
   *    baseTypesPath: types.ts
   *    filename: types.ts
   *  plugins:
   *    - typescript-operations
   *    - typescript-react-apollo
   * ```
   */
  filename: string;
};

export const preset: Types.OutputPreset<ModulesConfig> = {
  buildGeneratesSection: options => {
    const { baseOutputDir } = options;
    const { baseTypesPath } = options.presetConfig;

    const cwd = resolve(options.presetConfig.cwd || process.cwd());
    const importTypesNamespace = options.presetConfig.importTypesNamespace || 'Types';

    if (!baseTypesPath) {
      throw new Error(
        `Preset "modules" requires you to specify "baseTypesPath" configuration and point it to your base types file (generated by "typescript" plugin)!`
      );
    }

    if (!options.schemaAst || !options.schemaAst.extensions.sources) {
      throw new Error(`Preset "modules" requires to use SDL`);
    }

    const sourcesByModuleMap = groupSourcesByModule(options.schemaAst!.extensions.sources, baseOutputDir);
    const modules = Object.keys(sourcesByModuleMap);

    const pluginMap: { [name: string]: CodegenPlugin } = {
      ...options.pluginMap,
      add: addPlugin,
    };

    // One file with an output from all plugins
    const baseOutput: Types.GenerateOptions = {
      filename: resolve(cwd, baseOutputDir, baseTypesPath),
      schema: options.schema,
      documents: options.documents,
      plugins: options.plugins,
      pluginMap,
      config: options.config,
      schemaAst: options.schemaAst!,
    };

    const baseTypesFilename = baseTypesPath.replace(/\.(js|ts|d.ts)$/, '');
    const baseTypesDir = stripFilename(baseOutput.filename);

    // One file per each module
    const outputs: Types.GenerateOptions[] = modules.map(moduleName => {
      const filename = resolve(cwd, baseOutputDir, moduleName, options.presetConfig.filename);
      const dirpath = stripFilename(filename);
      const relativePath = relative(dirpath, baseTypesDir);
      const importPath = normalize(join(relativePath, baseTypesFilename)); // ../../types
      const sources = sourcesByModuleMap[moduleName];

      const moduleDocument = concatAST(
        sources.map(source =>
          parse(source.body, {
            noLocation: true,
          })
        )
      );

      return {
        filename,
        schema: options.schema,
        documents: [],
        plugins: [
          {
            add: buildModule(moduleDocument, {
              importNamespace: importTypesNamespace,
              importPath,
            }),
          },
        ],
        pluginMap: {
          add: addPlugin,
        },
        config: options.config,
        schemaAst: options.schemaAst,
      };
    });

    return [baseOutput].concat(outputs);
  },
};

export default preset;
