# Please add the labels which are applicable to all repos in The Guild Stack here

- name: 'automerge'
  color: '84e1f9'

- name: 'good first issue'
  color: '31be4f'

- name: 'kind/bug'
  color: '0052cc'
  description: 'Bug :-('
  from_name: 'bug'

- name: 'kind/enhancement'
  color: '0052cc'
  description: 'New feature or request'
  from_name: 'enhancement'

- name: 'kind/docs'
  color: '0052cc'
  description: 'Improvements or additions to documentation'
  from_name: 'docs'

- name: 'kind/question'
  color: '0052cc'
  description: 'Improvements or additions to documentation'

- name: 'bug/0-needs-repro'
  color: 'd73a4a'
  description: 'More information is needed for reproduction.'
  from_name: 'needs reproduction'

- name: 'bug/1-repro-available'
  color: 'd73a4a'
  description: 'A reproduction exists and needs to be confirmed.'

- name: 'bug/2-confirmed'
  color: 'd73a4a'
  description: 'We have confirmed that this is a bug.'

- name: 'waiting-for-answer'
  color: 'fef2c0'
  description: 'Waiting for answer from author'

- name: 'waiting-for-release'
  color: 'b6f3b1'
  description: 'Fixed/resolved, and waiting for the next stable release'

- name: 'duplicate'
  color: 'cfd8d7'
  description: 'This issue or pull request already exists'

- name: 'wontfix'
  color: '000000'
  description: 'This will not be worked on for now and is not in our backlog'
  from_name: 'wontfix'

- name: 'help wanted'
  color: '008672'
  description: 'Extra attention is needed'
  from_name: 'needs-help'

- name: 'process/candidate'
  color: '790e5d'
  description: 'Candidate for next Milestone.'

- name: 'status/backlog'
  color: 'b60205'
  description: 'In the backlog'

- name: 'status/wip'
  color: 'fbca04'
  description: 'Work In Progress'

- name: 'status/resolved'
  color: '0e8a16'
  description: 'The work has been completed'

- name: 'status/blocked'
  color: '243b29'
  description: 'This task is blocked by another dependant task'

- name: 'status/parked'
  color: 'bfd4f2'
  description: 'This task has been temporarily parked - No work is currently underway'

- name: 'status/pending-verification'
  color: 'c5def5'
  description: 'This task is complete but pending verification from the user'

# Please add the repo specific custom labels here

- name: 'core'
  color: '0366d6'
  description: "Related to codegen's core/cli"

- name: 'dependencies'
  color: 'd4c5f9'

- name: 'new-preset'
  color: '006b75'
  description: 'Suggestion for a new preset'

- name: 'plugins'
  color: 'c2e0c6'

- name: 'presets'
  color: '0e8a16'
  description: 'Related to Codegen presets'
