- name: 'bug'
  color: 'd73a4a'
  description: "Something isn't working"
- name: 'documentation'
  color: '0075ca'
  description: 'Improvements or additions to documentation'
- name: 'duplicate'
  color: 'cfd8d7'
  description: 'This issue or pull request already exists'
- name: 'enhancement'
  color: 'a22eef'
- name: 'wontfix_it'
  color: '000000'
  description: 'This will not be worked on'
  from_name: 'wontfix'
