template: |
  > Come talk to us directly on our [Discord channel](http://bit.ly/guild-chat)
  > Contact us here: [the-guild.dev](https://the-guild.dev/)

  ## What's planned for the next release?

  $CHANGES
