packages:
  - 'packages/*'
  - 'packages/utils/*'
  - 'packages/plugins/flow/*'
  - 'packages/plugins/java/*'
  - 'packages/plugins/c-sharp/*'
  - 'packages/plugins/typescript/*'
  - 'packages/plugins/other/*'
  - 'packages/presets/*'
  - 'website'
  - 'website/live-demo'
  - 'examples/*'
