name: '✨ Feature request'
description: Suggest an idea for the core of this project
body:
  - type: markdown
    attributes:
      value: |
        ## Is it related to a community plugin?

        All request linked to a "Community plugin" (as defined below) should [be addressed on the `dotansimha/graphql-code-generator-community` repository](https://github.com/dotansimha/graphql-code-generator-community/issues/new?assignees=&labels=&template=feature-request.md).

        <details>
          <summary>Community plugins:</summary>

        - `@graphql-codegen/typescript-react-apollo`
        - `@graphql-codegen/typescript-graphql-request`
        - `@graphql-codegen/typescript-apollo-angular`
        - `@graphql-codegen/typescript-apollo-client-helpers`
        - `@graphql-codegen/typescript-react-query`
        - `@graphql-codegen/typescript-urql`
        - `@graphql-codegen/named-operations-object`
        - `@graphql-codegen/urql-introspection`
        - `@graphql-codegen/flow-resolvers`
        - `@graphql-codegen/typescript-vue-apollo`
        - `@graphql-codegen/typescript-rtk-query`
        - `@graphql-codegen/flow-operations`
        - `@graphql-codegen/typescript-msw`
        - `@graphql-codegen/typescript-mongodb`
        - `@graphql-codegen/typescript-type-graphql`
        - `@graphql-codegen/jsdoc`
        - `@graphql-codegen/typescript-vue-urql`
        - `@graphql-codegen/kotlin`
        - `@graphql-codegen/typescript-vue-apollo-smart-ops`
        - `@graphql-codegen/java`
        - `@graphql-codegen/c-sharp-operations`
        - `@graphql-codegen/hasura-allow-list`
        - `@graphql-codegen/typescript-stencil-apollo`
        - `@graphql-codegen/relay-operation-optimizer`
        - `@graphql-codegen/typescript-oclif`
        - `@graphql-codegen/java-resolvers`
        - `@graphql-codegen/java-apollo-android`

        </details>

        ---
  - type: textarea
    id: description
    attributes:
      label: Is your feature request related to a problem? Please describe.
      description: "A clear and concise description of what the problem is. Ex. I'm always frustrated when [...]"
    validations:
      required: true
  - type: textarea
    id: solution
    attributes:
      label: Describe the solution you'd like
      description: 'A clear and concise description of what you want to happen.'
    validations:
      required: true
  - type: textarea
    id: alternatives
    attributes:
      label: Describe alternatives you've considered
      description: "A clear and concise description of any alternative solutions or features you've considered."
    validations:
      required: false
  - type: textarea
    id: context
    attributes:
      label: Is your feature request related to a problem? Please describe.
      description: 'Add any other context or screenshots about the feature request here.'
    validations:
      required: false
