/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */

import '@stencil/core';

import 'stencil-apollo';

export namespace Components {
  interface MyComponentWithCodegen {
    first: string;
    last: string;
  }
  interface MyComponentWithCodegenAttributes extends StencilHTMLAttributes {
    first?: string;
    last?: string;
  }
}

declare global {
  interface StencilElementInterfaces {
    MyComponentWithCodegen: Components.MyComponentWithCodegen;
  }

  interface StencilIntrinsicElements {
    'my-component-with-codegen': Components.MyComponentWithCodegenAttributes;
  }

  interface HTMLMyComponentWithCodegenElement extends Components.MyComponentWithCodegen, HTMLStencilElement {}
  var HTMLMyComponentWithCodegenElement: {
    prototype: HTMLMyComponentWithCodegenElement;
    new (): HTMLMyComponentWithCodegenElement;
  };

  interface HTMLElementTagNameMap {
    'my-component-with-codegen': HTMLMyComponentWithCodegenElement;
  }

  interface ElementTagNameMap {
    'my-component-with-codegen': HTMLMyComponentWithCodegenElement;
  }

  export namespace JSX {
    export interface Element {}
    export interface IntrinsicElements extends StencilIntrinsicElements {
      [tagName: string]: any;
    }
  }
  export interface HTMLAttributes extends StencilHTMLAttributes {}
}
