name: pr
on:
  pull_request:
    branches:
      - master

jobs:
  dependencies:
    uses: the-guild-org/shared-config/.github/workflows/changesets-dependencies.yaml@8a92265b03efb0c3626397f993adcb1738e459e4 # main
    if: ${{ github.event.pull_request.title != 'Upcoming Release Changes' }}
    permissions:
      contents: write # allows modifying changeset files
    secrets:
      githubToken: ${{ secrets.GITHUB_TOKEN }}
