name: pr
on:
  pull_request:
    branches:
      - master

jobs:
  dependencies:
    uses: the-guild-org/shared-config/.github/workflows/changesets-dependencies.yaml@1c4632ccc198d4c9b34d9e6b3d556c6f245b4e69 # main
    if: ${{ github.event.pull_request.title != 'Upcoming Release Changes' }}
    permissions:
      contents: write # allows modifying changeset files
    secrets:
      githubToken: ${{ secrets.GITHUB_TOKEN }}
