name: Website Integrity
on:
  pull_request:
    paths:
      - 'website/**'
jobs:
  website-check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4

      - name: Fetch
        run: git fetch origin master

      - name: Setup env
        uses: the-guild-org/shared-config/setup@main
        with:
          nodeVersion: 18

      - name: Build Packages
        run: yarn build

      - name: Build Website
        run: yarn workspace website run build

      - name: Compare
        run: git diff origin/${{ github.base_ref }}.. -- website/route-lockfile.txt

      - name: Diff to file
        if: always()
        id: diff_result
        run: |
          OUTPUT=$(git diff origin/${{ github.base_ref }}.. -- website/route-lockfile.txt)
          OUTPUT="${OUTPUT//'%'/'%25'}"
          OUTPUT="${OUTPUT//$'\n'/'%0A'}"
          OUTPUT="${OUTPUT//$'\r'/'%0D'}"
          echo "::set-output name=result::$OUTPUT"

      - name: Publish a message
        if: always() && contains(steps.diff_result.outputs.result, 'diff')
        uses: marocchino/sticky-pull-request-comment@52423e01640425a022ef5fd42c6fb5f633a02728 # v2
        with:
          message: |
            ```diff
            ${{ steps.diff_result.outputs.result }}
            ```
